# Generated by Django 3.2.9 on 2021-12-27 06:34

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='ニックネーム')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='注文者名')),
                ('addressnumber', models.CharField(blank=True, max_length=9, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='メールアドレス')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='配達日')),
                ('order_time', models.IntegerField(blank=True, null=True, verbose_name='配達時間')),
                ('tel', models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='注文状況')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('coffee_detail', models.CharField(max_length=200, verbose_name='商品詳細')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.upload_coffee_path)),
                ('coffee_priceL', models.IntegerField(verbose_name='商品Lサイズ料金')),
                ('coffee_priceM', models.IntegerField(verbose_name='商品Mサイズ料金')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=100, verbose_name='トッピング名')),
                ('topping_priceL', models.IntegerField(verbose_name='トッピングLサイズ料金')),
                ('topping_priceM', models.IntegerField(verbose_name='トッピングMサイズ料金')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(verbose_name='数量')),
                ('item_size', models.CharField(max_length=6, verbose_name='商品サイズ')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='api.carts')),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coffee')),
                ('toppings', models.ManyToManyField(blank=True, to='api.Topping')),
            ],
        ),
    ]
