# Generated by Django 3.2.9 on 2021-12-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user'),
            preserve_default=False,
        ),
    ]
