# Generated by Django 3.2.9 on 2021-12-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.AddField(
            model_name='carts',
            name='userCart',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='userCart', to='api.user'),
            preserve_default=False,
        ),
    ]
