# Generated by Django 3.2.9 on 2021-12-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211227_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='order_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='配達時間'),
        ),
    ]
